name: Build
on:
  push:
    branches:
      - github-actions
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/setup-ruby@v1
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: true
          ref: github-actions
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python3 -m pip install -U pip
          pip3 install hammock python-dateutil datetime termcolor purl python-magic
      - name: Copy Token
        run: echo ${{ secrets.GITHUB_TOKEN }} > gh\ token.txt
      - name: Check Parallel
        run: python3 -u parallel_check.py
      - name: Install Build Dependencies
        run: |
          HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install acpica libmagic mingw-w64 openssl
      - name: Set Up Working Tree
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git clone https://github.com/dortania/build-repo.git Config --depth 1 --single-branch --branch builds --sparse --filter=blob:none
      - uses: fregante/setup-git-user@v1
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2
      - name: Send Starting Notification
        if: always()
        env:
          JOB_STATUS: started
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
          JOB_ID: ${{ github.job }}
        run: |
          git clone https://github.com/dhinakg/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
      - name: Run Builder
        run: python3 -u updater.py
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py
      - name: Sort Config
        run: python3 -u update_config.py
      - name: Send Notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
          JOB_ID: ${{ github.job }}
        run: |
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
